
name: Deploy existing React TS build to Azure Web App - staging-exskilence

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies (optional, only if needed for runtime)
        run: npm install --legacy-peer-deps

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'staging-exskilence'
          slot-name: 'Production'
          package: ./build
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8789DBBAAE8A44FDA837FFC01678D515 }}

